# Generated by Django 6.0.7 on 2026-08-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sensor_reading', models.FloatField()),
                ('severity_score', models.IntegerField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
